<?php

/**
 * @file
 *
 * Defines all the hooks this module implements.
 *
 * @todo Since we don't have the tabs module, we need to create paths for Books.
 */

// Permissions
define('PERM_ISLANDORA_BOOK_DELETE_PAGE', 'delete pages');
define('PERM_ISLANDORA_BOOK_MANAGE_BOOK', 'manage book object');
define('PERM_ISLANDORA_BOOK_MANAGE_PAGE', 'manage page object');
define('PERM_ISLANDORA_BOOK_MANAGE_DELETED_BOOKS', 'manage deleted books');

/**
 * Implements hook_menu().
 */
function islandora_book_menu() {
  return array(
    'admin/islandora/book' => array(
      'title' => 'Book Collection',
      'description' => 'Configuration the Book solution pack.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_book_admin_settings_form'),
      'access arguments' => array('administer site configuration'),
      'file' => 'includes/admin.form.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
    'islandora/object/%islandora_object/pages' => array(
      'title' => 'Pages',
      'type' => MENU_LOCAL_TASK,
      'page callback' => 'islandora_book_pages_menu',
      'page arguments' => array(2),
      'access callback' => 'islandora_object_access_callback',
      'access arguments' => array(FEDORA_VIEW, 2),
      'file' => 'includes/pages.menu.inc',
    )
  );
    /*
    'restore/books' => array(
      'title' => t('Deleted Books'),
      'file' => 'management/book_undelete.inc',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('book_undelete_form'),
      'access arguments' => array(PERM_ISLANDORA_BOOK_MANAGE_DELETED_BOOKS),
      'type' => MENU_NORMAL_ITEM,
    ),
    'islandora/book/updatepage' => array(
      'page callback' => 'page_management_wrapper',
      'access arguments' => array(PERM_ISLANDORA_BOOK_MANAGE_BOOK),
      'file' => 'ObjectManager.inc',
      'type' => MENU_CALLBACK,
    ),
    'islandora/book/upload' => array(
      'page callback' => 'upload_pages',
      'access arguments' => array(PERM_ISLANDORA_BOOK_MANAGE_BOOK),
      'file' => 'pageload/upload_frame.inc',
      'type' => MENU_CALLBACK,
    ),
    'islandora/book/borndigital' => array(
      'page callback' => 'create_borndigital',
      'access arguments' => array(FEDORA_VIEW),
      'file' => 'management/born_digital.inc',
      'type' => MENU_CALLBACK,
    ),
    'islandora/book/upload_setup' => array(
      'page callback' => 'upload_setup',
      'access arguments' => array(PERM_ISLANDORA_BOOK_MANAGE_BOOK),
      'file' => 'pageload/upload_frame.inc',
      'type' => MENU_CALLBACK,
    ),
    'islandora/book/process_file' => array(
      'page callback' => 'process_file',
      'access arguments' => array(FEDORA_VIEW),
      'file' => 'pageload/upload_frame.inc',
      'type' => MENU_CALLBACK,
    ),
    'islandora/book/process_page_directory' => array(
      'page callback' => 'prep_add_form',
      'access arguments' => array(FEDORA_VIEW),
      'file' => 'pageload/prepare_add_pages_form.inc',
      'type' => MENU_CALLBACK,
    ),
    'islandora/book/delete_book_files' => array(
      'page callback' => 'delete_book_page_files',
      'access arguments' => array(FEDORA_VIEW),
      'file' => 'pageload/upload_frame.inc',
      'type' => MENU_CALLBACK,
    ),
    'islandora/page/manage' => array(
      'page callback' => 'islandora_book_page_management',
      'access arguments' => array(PERM_ISLANDORA_BOOK_MANAGE_PAGE),
      'file' => 'page_object_manager.inc',
      'type' => MENU_CALLBACK,
    ),
    'islandora/book/manage' => array(
      'page callback' => 'islandora_book_display_links',
      'access arguments' => array(PERM_ISLANDORA_BOOK_MANAGE_BOOK),
      'file' => 'management/IslandoraBookDisplayLinks.inc',
      'type' => MENU_CALLBACK,
    ),
    'islandora/book/management' => array(
      'page callback' => 'book_management_wrapper',
      'access arguments' => array(PERM_ISLANDORA_BOOK_MANAGE_BOOK),
      'file' => 'book_object_manager.inc',
      'type' => MENU_CALLBACK,
      )
  );
*/
}

/**
 * Implements hook_perm().
 */
function islandora_book_perm() {
  return array(
    PERM_ISLANDORA_BOOK_DELETE_PAGE,
    PERM_ISLANDORA_BOOK_MANAGE_BOOK,
    PERM_ISLANDORA_BOOK_MANAGE_PAGE,
    PERM_ISLANDORA_BOOK_MANAGE_DELETED_BOOKS
  );
}

/**
 * Implementation of hook_theme().
 */
function islandora_book_theme() {
  return array(
    'islandora_book_book' => array(
      'arguments' => array('object' => NULL),
      'file' => 'theme/islandora_book.theme.inc',
      'template' => 'theme/islandora-book'
    ),
    'islandora_book_page' => array(
      'arguments' => array('object' => NULL),
      'file' => 'theme/islandora_book.theme.inc',
      'template' => 'theme/islandora-page'
    ),
    'islandora_book_pages' => array(
      'arguments' => array('object' => NULL),
      'file' => 'theme/islandora_book.theme.inc',
      'template' => 'theme/islandora-pages'
    ),
    'islandora_book_pages_grid' => array(
      'arguments' => array('object' => NULL),
      'file' => 'theme/islandora_book.theme.inc',
      'template' => 'theme/islandora-pages-grid'
    ),
    'islandora_book_pages_list' => array(
      'arguments' => array('object' => NULL),
      'file' => 'theme/islandora_book.theme.inc',
      'template' => 'theme/islandora-pages-list'
    ),
    /*
      'islandora_book_page_table' => array(
      'arguments' => array('element' => NULL),
      'file' => 'management/IslandoraBookPageTable.inc',
    ),
    'islandora_book_page_reorder_table' => array(
      'arguments' => array('element' => NULL),
      'file' => 'management/IslandoraPageReorderTable.inc',
    ),
    'islandora_book_undelete_table' => array(
      'arguments' => array('element' => NULL),
      'file' => 'management/IslandoraBookUndelete.inc',
    ),
    'islandora_file_reorder_table' => array(
      'arguments' => array('element' => NULL),
      'file' => 'management/IslandoraFileReorderTable.inc',
      )*/
  );
}

/**
 * Implements hook_help().
 */
function islandora_book_help($path, $arg) {
  switch ($path) {
    case 'admin/help#islandora_book':
      return t('<p>The Islandora Book Module allows users to create digital
                representations of books within the Fedora Repository. A book
                object is created using !mods data. A collection of associated
                page objects may then be created created. Page objects are
                created by ingesting a zipped folder of TIFF images, each
                representing a distinct page. Page TIFFs are used to create a
                series of Fedora datastreams on ingestion.  These streams
                include derivative images for display - JPEGS, Thumbnails, and
                JP2s, and one ore more OCR streams for text display and analysis
                </p>
                <h3>Configuration</h3>
                <p>The page datatreams may be created on this server, or on an
                external processing server with !microservices.<br/> To process
                images from TIFFS on this server check <strong>Create derivative
                images locally?</strong> on the admin page. (Link at the bottom
                of this page).<br/> TO create OCR streams on this server check
                <strong>Perform OCR on incoming TIFF images?</strong>.<br/><br/>
                </p>', array(
                  '!microservices' => l("Fedora Microservices", 'https://github.com/Islandora/fedora_microservices'),
                  '!mods' => l('MODS', 'http://www.loc.gov/standards/mods/'))
      );
  }
}

/**
 * Implements hook_islandora_xml_form_builder_form_associations().
 */
function islandora_book_islandora_xml_form_builder_form_associations() {
  return array(
    'islandora_book_mods_form' => array(
      'content_model' => 'islandora:bookCModel',
      'form_name' => 'Islandora Book MODS Form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
    'islandora_book_ia_mods_form' => array(
      'content_model' => 'islandora:iabookCModel',
      'form_name' => 'Islandora Book MODS Form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    )
  );
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_book_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_book');
  return array(
    'Islandora Book MODS form' => array(
      'form_file' => "$module_path/data/forms/book_mods_form.xml",
    ),
    'Islandora Book Page MODS form' => array(
      'form_file' => "$module_path/data/forms/page_mods_form.xml",
    ),
  );
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_book_islandora_required_objects(IslandoraTuque $connection) {
  $module_path = drupal_get_path('module', 'islandora_book');
  // Page Content Model
  $page_content_model = $connection->repository->constructObject('islandora:pageCModel');
  $page_content_model->owner = 'fedoraAdmin';
  $page_content_model->label = 'Islandora Page Content Model';
  $page_content_model->models = 'fedora-system:ContentModel-3.0';
  $page_content_model->relationships->add(FEDORA_MODEL_URI, 'hasService', 'islandora:viewerSdef');
  $page_content_model->relationships->add(FEDORA_MODEL_URI, 'hasService', 'islandora:jp2Sdef');
  $page_content_model->relationships->add(FEDORA_MODEL_URI, 'hasService', 'islandora:tei2htmlSdef');
  // DS-COMPOSITE-MODEL Datastream
  $datastream = $page_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'M');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_pageCModel_ds_composite_model.xml", FALSE);
  $page_content_model->ingestDatastream($datastream);
  // Internet Archive Book Content Model
  $ia_book_content_model = $connection->repository->constructObject('islandora:iabookCModel');
  $ia_book_content_model->owner = 'fedoraAdmin';
  $ia_book_content_model->label = 'Islandora Internet Archive Book Content Model';
  $ia_book_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream
  $datastream = $ia_book_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'M');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_iabookCModel_ds_composite_model.xml", FALSE);
  $ia_book_content_model->ingestDatastream($datastream);
  // Book Collection
  $book_collection = $connection->repository->constructObject('islandora:bookCollection');
  $book_collection->owner = 'fedoraAdmin';
  $book_collection->label = 'Book Collection';
  $book_collection->models = 'islandora:collectionCModel';
  $book_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'islandora:root');
  // Collection Policy Datastream
  $datastream = $book_collection->constructDatastream('COLLECTION_POLICY', 'M');
  $datastream->label = 'COLLECTION_POLICY';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_book_collection_policy.xml", FALSE);
  $book_collection->ingestDatastream($datastream);
  // TN Datastream
  $datastream = $book_collection->constructDatastream('TN', 'M');
  $datastream->label = 'TN';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png", FALSE);
  $book_collection->ingestDatastream($datastream);
  return array(
    'islandora_book'=> array(
      'title' => 'Islandora book',
      'objects' => array(
        $page_content_model,
        $ia_book_content_model,
        $book_collection
      )
    )
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_book_islandora_iabookcmodel_islandora_view_object($object) {
  $output = theme('islandora_book_book', array('object' => $object));
  return array('islandora_book' => $output);
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_book_islandora_pagecmodel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_book_page', array('object' => $object));
  return array('islandora_book' => $output);
}


/**
 * Displays the Internet Archive BookReader.
 *
 * @global user $user
 *   Used to pass user credentials to fedora.
 * @param string $object_id
 *   The identifier of the book object to view.
 *
 * @return string
 *   A fieldset containing the Internet Archive BookReader.
 */
function islandora_book_viewer($object_id) {
  global $user;
  $query = ($user->uid != 0) ? '?uid=' . base64_encode($user->name . ':' . $user->pass) : '';
  $viewer_url = variable_get('islandora_base_url', 'http://localhost:8080/fedora');
  $viewer_url .= "/get/{$object_id}/islandora:viewerSdef/getViewer{$query}";
  return theme('fieldset', array(
      '#title' => t('Viewer - @object_id', array('@object_id' => $object_id)),
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
      '#value' => "<iframe src='{$viewer_url}' frameborder='0' scrolling='no' style='width: 100%; height: 800px;'>Errors: unable to load viewer</iframe>"
    )
  );
}

/**
 * @todo Make each tab into a seperate menu Path.
 */
function islandora_book_islandora_tabs($content_models, $pid) {
  module_load_include('inc', 'islandora_book', 'page_object_manager');
  module_load_include('inc', 'islandora_book', 'book_object_manager');
  module_load_include('inc', 'fedora_repository', 'plugins/FedoraObjectDetailedContent');
  $tabset = array();
  $content_model = $content_models[0]->pid;
  if ($content_model == 'islandora:pageCModel' && user_access(PERM_ISLANDORA_BOOK_MANAGE_PAGE)) {
    $return_tabs = get_page_model_management_content($pid);
    $return_tabs['fedora_object_details'] = null;
    return $return_tabs;
  }
  if ($content_model == 'islandora:bookCModel' || $content_model == 'islandora:iaBookCModel') {
    $return_tabs['fedora_object_details'] = null;
    return $return_tabs;
  }
}
