<?php

/**
 * @file
 *
 * Defines all the hooks this module implements.
 *
 * @todo Since we don't have the tabs module, we need to create paths for Books.
 */

// Permissions
define('PERM_ISLANDORA_BOOK_DELETE_PAGE', 'delete pages');
define('PERM_ISLANDORA_BOOK_MANAGE_BOOK', 'manage book object');
define('PERM_ISLANDORA_BOOK_MANAGE_PAGE', 'manage page object');
define('PERM_ISLANDORA_BOOK_MANAGE_DELETED_BOOKS', 'manage deleted books');
// Variables


/**
 * Implements hook_menu().
 */
function islandora_book_menu() {
  return array(
    'admin/islandora/book' => array(
      'title' => 'Book Collection',
      'description' => 'Configuration the Book solution pack.',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('islandora_book_admin_settings_form'),
      'access arguments' => array('administer site configuration'),
      'file' => 'islandora_book.admin.inc',
      'type' => MENU_NORMAL_ITEM,
    ),
    'fedora/book/%islandora_object/%' => array(
      'title' => t('Book view'),
      'page callback' => 'islandora_book_create_book_view',
      'page arguments' => array(2, 3),
      'access arguments' => array(FEDORA_VIEW),
      'type' => MENU_CALLBACK,
    ),
    'restore/books' => array(
      'title' => t('Deleted Books'),
      'file' => 'management/book_undelete.inc',
      'page callback' => 'drupal_get_form',
      'page arguments' => array('book_undelete_form'),
      'access arguments' => array(PERM_ISLANDORA_BOOK_MANAGE_DELETED_BOOKS),
      'type' => MENU_NORMAL_ITEM,
    ),
    'fedora/book_viewer' => array(
      'title' => t('Book viewer'),
      'page callback' => 'islandora_book_viewer',
      'access arguments' => array(FEDORA_VIEW),
      'type' => MENU_CALLBACK,
    ),
    'islandora/book/ocr' => array(
      'page callback' => 'update_ocr_div',
      'access arguments' => array(FEDORA_VIEW),
      'file' => 'islandora_book.admin.inc',
      'type' => MENU_CALLBACK,
    ),
    'islandora/book/updatepage' => array(
      'page callback' => 'page_management_wrapper',
      'access arguments' => array(PERM_ISLANDORA_BOOK_MANAGE_BOOK),
      'file' => 'ObjectManager.inc',
      'type' => MENU_CALLBACK,
    ),
    'islandora/book/upload' => array(
      'page callback' => 'upload_pages',
      'access arguments' => array(PERM_ISLANDORA_BOOK_MANAGE_BOOK),
      'file' => 'pageload/upload_frame.inc',
      'type' => MENU_CALLBACK,
    ),
    'islandora/book/borndigital' => array(
      'page callback' => 'create_borndigital',
      'access arguments' => array(FEDORA_VIEW),
      'file' => 'management/born_digital.inc',
      'type' => MENU_CALLBACK,
    ),
    'islandora/book/upload_setup' => array(
      'page callback' => 'upload_setup',
      'access arguments' => array(PERM_ISLANDORA_BOOK_MANAGE_BOOK),
      'file' => 'pageload/upload_frame.inc',
      'type' => MENU_CALLBACK,
    ),
    'islandora/book/process_file' => array(
      'page callback' => 'process_file',
      'access arguments' => array(FEDORA_VIEW),
      'file' => 'pageload/upload_frame.inc',
      'type' => MENU_CALLBACK,
    ),
    'islandora/book/process_page_directory' => array(
      'page callback' => 'prep_add_form',
      'access arguments' => array(FEDORA_VIEW),
      'file' => 'pageload/prepare_add_pages_form.inc',
      'type' => MENU_CALLBACK,
    ),
    'islandora/book/delete_book_files' => array(
      'page callback' => 'delete_book_page_files',
      'access arguments' => array(FEDORA_VIEW),
      'file' => 'pageload/upload_frame.inc',
      'type' => MENU_CALLBACK,
    ),
    'islandora/page/manage' => array(
      'page callback' => 'islandora_book_page_management',
      'access arguments' => array(PERM_ISLANDORA_BOOK_MANAGE_PAGE),
      'file' => 'page_object_manager.inc',
      'type' => MENU_CALLBACK,
    ),
    'islandora/book/manage' => array(
      'page callback' => 'islandora_book_display_links',
      'access arguments' => array(PERM_ISLANDORA_BOOK_MANAGE_BOOK),
      'file' => 'management/IslandoraBookDisplayLinks.inc',
      'type' => MENU_CALLBACK,
    ),
    'islandora/book/management' => array(
      'page callback' => 'book_management_wrapper',
      'access arguments' => array(PERM_ISLANDORA_BOOK_MANAGE_BOOK),
      'file' => 'book_object_manager.inc',
      'type' => MENU_CALLBACK,
    )
  );
}

/**
 * Implements hook_perm().
 */
function islandora_book_perm() {
  return array(
    PERM_ISLANDORA_BOOK_DELETE_PAGE,
    PERM_ISLANDORA_BOOK_MANAGE_BOOK,
    PERM_ISLANDORA_BOOK_MANAGE_PAGE,
    PERM_ISLANDORA_BOOK_MANAGE_DELETED_BOOKS
  );
}

/**
 * Implementation of hook_theme().
 */
function islandora_book_theme() {
  return array(
    'islandora_book_book_view' => array(
      'arguments' => array('object' => NULL),
      'template' => 'theme/islandora-book-view'
    ),
    'islandora_book_page_view' => array(
      'arguments' => array('object' => NULL),
      'template' => 'theme/islandora-page-view'
    ),
    'islandora_book_book_search_form' => array(
      'arguments' => array('form' => NULL),
    ),
    'islandora_book_simple_book_search_form' => array(
      'arguments' => array('form' => NULL),
    ),
    'islandora_book_page_table' => array(
      'arguments' => array('element' => NULL),
      'file' => 'management/IslandoraBookPageTable.inc',
    ),
    'islandora_book_page_reorder_table' => array(
      'arguments' => array('element' => NULL),
      'file' => 'management/IslandoraPageReorderTable.inc',
    ),
    'islandora_book_undelete_table' => array(
      'arguments' => array('element' => NULL),
      'file' => 'management/IslandoraBookUndelete.inc',
    ),
    'islandora_file_reorder_table' => array(
      'arguments' => array('element' => NULL),
      'file' => 'management/IslandoraFileReorderTable.inc',
    )
  );
}

/**
 * Implements hook_help().
 */
function islandora_book_help($path, $arg) {
  switch ($path) {
    case 'admin/help#islandora_book':
      return t('<p>The Islandora Book Module allows users to create digital
                representations of books within the Fedora Repository. A book
                object is created using !mods data. A collection of associated
                page objects may then be created created. Page objects are
                created by ingesting a zipped folder of TIFF images, each
                representing a distinct page. Page TIFFs are used to create a
                series of Fedora datastreams on ingestion.  These streams
                include derivative images for display - JPEGS, Thumbnails, and
                JP2s, and one ore more OCR streams for text display and analysis
                </p>
                <h3>Configuration</h3>
                <p>The page datatreams may be created on this server, or on an
                external processing server with !microservices.<br/> To process
                images from TIFFS on this server check <strong>Create derivative
                images locally?</strong> on the admin page. (Link at the bottom
                of this page).<br/> TO create OCR streams on this server check
                <strong>Perform OCR on incoming TIFF images?</strong>.<br/><br/>
                </p>', array(
                  '!microservices' => l("Fedora Microservices", 'https://github.com/Islandora/fedora_microservices'),
                  '!mods' => l('MODS', 'http://www.loc.gov/standards/mods/'))
      );
  }
}

/**
 * Implements hook_islandora_xml_form_builder_form_associations().
 */
function islandora_book_islandora_xml_form_builder_form_associations() {
  return array(
    'islandora_book_mods_form' => array(
      'content_model' => 'islandora:bookCModel',
      'form_name' => 'Islandora Book MODS Form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    ),
    'islandora_book_ia_mods_form' => array(
      'content_model' => 'islandora:iabookCModel',
      'form_name' => 'Islandora Book MODS Form',
      'dsid' => 'MODS',
      'title_field' => array('titleInfo', 'title'),
      'transform' => 'mods_to_dc.xsl',
      'template' => FALSE,
    )
  );
}

/**
 * Implements hook_islandora_xml_form_builder_forms().
 */
function islandora_book_islandora_xml_form_builder_forms() {
  $module_path = drupal_get_path('module', 'islandora_book');
  return array(
    'Islandora Book MODS form' => array(
      'form_file' => "$module_path/xml/mods_books.xml",
    ),
  );
}

/**
 * Implements hook_islandora_required_objects().
 */
function islandora_book_islandora_required_objects() {
  $module_path = drupal_get_path('module', 'islandora_book');
  $connection = islandora_get_tuque_connection();
  // Page Content Model
  $page_content_model = $connection->repository->constructObject('islandora:pageCModel');
  $page_content_model->owner = 'fedoraAdmin';
  $page_content_model->label = 'Page Content Model';
  $page_content_model->models = 'fedora-system:ContentModel-3.0';
  $page_content_model->relationships->add(FEDORA_MODEL_URI, 'hasService', 'info:fedora/islandora:viewerSdef');
  $page_content_model->relationships->add(FEDORA_MODEL_URI, 'hasService', 'info:fedora/islandora:jp2Sdef');
  $page_content_model->relationships->add(FEDORA_MODEL_URI, 'hasService', 'info:fedora/islandora:tei2htmlSdef');
  // DS-COMPOSITE-MODEL Datastream
  $datastream = $page_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'M');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_pageCModel_ds_composite_model.xml");
  // Born Digitial Page Content Model
  $bd_page_content_model = $connection->repository->constructObject('islandora:bd_pageCModel');
  $bd_page_content_model->owner = 'fedoraAdmin';
  $bd_page_content_model->label = 'Born Digitial Page Content Model';
  $bd_page_content_model->models = 'fedora-system:ContentModel-3.0';
  $bd_page_content_model->relationships->add(FEDORA_MODEL_URI, 'hasService', 'info:fedora/islandora:viewerSdef');
  $bd_page_content_model->relationships->add(FEDORA_MODEL_URI, 'hasService', 'info:fedora/islandora:jp2Sdef');
  $bd_page_content_model->relationships->add(FEDORA_MODEL_URI, 'hasService', 'info:fedora/islandora:tei2htmlSdef');
  // DS-COMPOSITE-MODEL Datastream
  $datastream = $bd_page_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'M');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_bd_pageCModel_ds_composite_model.xml");
  // Internet Archive Book Content Model
  $ia_book_content_model = $connection->repository->constructObject('islandora:iabookCModel');
  $ia_book_content_model->owner = 'fedoraAdmin';
  $ia_book_content_model->label = 'Internet Archive Book Content Model';
  $ia_book_content_model->models = 'fedora-system:ContentModel-3.0';
  // DS-COMPOSITE-MODEL Datastream
  $datastream = $ia_book_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'M');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_iabookCModel_ds_composite_model.xml");
  // Book Content Model
  $book_content_model = $connection->repository->constructObject('islandora:bookCModel');
  $book_content_model->owner = 'fedoraAdmin';
  $book_content_model->label = 'Book Content Model';
  $book_content_model->models = 'fedora-system:ContentModel-3.0';
  $book_content_model->relationships->add(FEDORA_MODEL_URI, 'hasService', 'info:fedora/islandora:viewerSdef');
  // DS-COMPOSITE-MODEL Datastream
  $datastream = $book_content_model->constructDatastream('DS-COMPOSITE-MODEL', 'M');
  $datastream->label = 'DS-COMPOSITE-MODEL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_bookCModel_ds_composite_model.xml");
  // JP2 Service Definition
  $jp2_service_definition = $connection->repository->constructObject('islandora:jp2Sdef');
  $jp2_service_definition->owner = 'fedoraAdmin';
  $jp2_service_definition->label = 'JP2 Service Definition';
  $jp2_service_definition->models = 'fedora-system:ServiceDefinition-3.0';
  // METHODMAP Datastream
  $datastream = $jp2_service_definition->constructDatastream('METHODMAP', 'M');
  $datastream->label = 'METHODMAP';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_jp2Sdef_methodmap.xml");
  // JP2 Service Deployment for the Page Content Model
  $jp2_service_deployment_page = $connection->repository->constructObject('islandora:jp2Sdep-pageCModel');
  $jp2_service_deployment_page->owner = 'fedoraAdmin';
  $jp2_service_deployment_page->label = 'Jp2 Service Deployment for the Page Content Model';
  $jp2_service_deployment_page->models = 'fedora-system:ServiceDeployment-3.0';
  $jp2_service_deployment_page->relationships->add(FEDORA_MODEL_URI, 'isDeploymentOf', 'info:fedora/islandora:jp2Sdef');
  $jp2_service_deployment_page->relationships->add(FEDORA_MODEL_URI, 'isContractorOf', 'info:fedora/islandora:pageCModel');
  $jp2_service_deployment_page->relationships->add(FEDORA_MODEL_URI, 'isContractorOf', 'info:fedora/newspapers:pageCModel');
  // DSINPUTSPEC Datastream
  $datastream = $jp2_service_deployment_page->constructDatastream('DSINPUTSPEC', 'M');
  $datastream->label = 'DSINPUTSPEC';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_jp2Sdep_pageCModel_dsinputspec.xml");
  // METHODMAP Datastream
  $datastream = $jp2_service_deployment_page->constructDatastream('METHODMAP', 'M');
  $datastream->label = 'METHODMAP';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_jp2Sdep_pageCModel_methodmap.xml");
  // WSDL Datastream
  $datastream = $jp2_service_deployment_page->constructDatastream('WSDL', 'M');
  $datastream->label = 'WSDL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_jp2Sdep_pageCModel_wsdl.xml");
  // Viewer Service Definition
  $viewer_service_definition = $connection->repository->constructObject('islandora:viewerSdef');
  $viewer_service_definition->owner = 'fedoraAdmin';
  $viewer_service_definition->label = 'Viewer Service Definition';
  $viewer_service_definition->models = 'fedora-system:ServiceDefinition-3.0';
  // METHODMAP Datastream
  $datastream = $viewer_service_definition->constructDatastream('METHODMAP', 'M');
  $datastream->label = 'METHODMAP';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_viewerSdef_methodmap.xml");
  // Viewer Service Deployment for the Book Content Model
  $viewer_service_deployment_book = $connection->repository->constructObject('islandora:viewerSdep-bookCModel');
  $viewer_service_deployment_book->owner = 'fedoraAdmin';
  $viewer_service_deployment_book->label = 'Viewer Service Deployment for the Book Content Model';
  $viewer_service_deployment_book->models = 'fedora-system:ServiceDeployment-3.0';
  $viewer_service_deployment_book->relationships->add(FEDORA_MODEL_URI, 'isDeploymentOf', 'info:fedora/islandora:viewerSdef');
  $viewer_service_deployment_book->relationships->add(FEDORA_MODEL_URI, 'isContractorOf', 'info:fedora/islandora:bookCModel');
  // DSINPUTSPEC Datastream
  $datastream = $viewer_service_deployment_book->constructDatastream('DSINPUTSPEC', 'M');
  $datastream->label = 'DSINPUTSPEC';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_viewerSdep_bookCModel_dsinputspec.xml");
  // METHODMAP Datastream
  $datastream = $viewer_service_deployment_book->constructDatastream('METHODMAP', 'M');
  $datastream->label = 'METHODMAP';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_viewerSdep_bookCModel_methodmap.xml");
  // WSDL Datastream
  $datastream = $viewer_service_deployment_book->constructDatastream('WSDL', 'M');
  $datastream->label = 'WSDL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_viewerSdep_bookCModel_wsdl.xml");
  // Viewer Service Deployment for the Page Content Model
  $viewer_service_deployment_page = $connection->repository->constructObject('islandora:viewerSdep-pageCModel');
  $viewer_service_deployment_page->owner = 'fedoraAdmin';
  $viewer_service_deployment_page->label = 'Viewer Service Deployment for the Page Content Model';
  $viewer_service_deployment_page->models = 'fedora-system:ServiceDeployment-3.0';
  $viewer_service_deployment_page->relationships->add(FEDORA_MODEL_URI, 'isDeploymentOf', 'info:fedora/islandora:viewerSdef');
  $viewer_service_deployment_page->relationships->add(FEDORA_MODEL_URI, 'isContractorOf', 'info:fedora/islandora:pageCModel');
  // DSINPUTSPEC Datastream
  $datastream = $viewer_service_deployment_page->constructDatastream('DSINPUTSPEC', 'M');
  $datastream->label = 'DSINPUTSPEC';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_viewerSdep_pageCModel_dsinputspec.xml");
  // METHODMAP Datastream
  $datastream = $viewer_service_deployment_page->constructDatastream('METHODMAP', 'M');
  $datastream->label = 'METHODMAP';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_viewerSdep_pageCModel_methodmap.xml");
  // WSDL Datastream
  $datastream = $viewer_service_deployment_page->constructDatastream('WSDL', 'M');
  $datastream->label = 'WSDL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_viewerSdep_pageCModel_wsdl.xml");
  // TEI 2 HTML Service Definition
  $tei2html_service_definition = $connection->repository->constructObject('islandora:tei2htmlSdef');
  $tei2html_service_definition->owner = 'fedoraAdmin';
  $tei2html_service_definition->label = 'TEI 2 HTML Service Definition';
  $tei2html_service_definition->models = 'fedora-system:ServiceDefinition-3.0';
  // METHODMAP Datastream
  $datastream = $tei2html_service_definition->constructDatastream('METHODMAP', 'M');
  $datastream->label = 'METHODMAP';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_tei2htmlSdef_methodmap.xml");
  // TEI 2 HTML Service Depolyment for the Page Content Model
  $tei2html_service_deployment_page = $connection->repository->constructObject('islandora:tei2htmlSdep-pageCModel');
  $tei2html_service_deployment_page->owner = 'fedoraAdmin';
  $tei2html_service_deployment_page->label = 'TEI 2 HTML Service Deployment for the Page Content Model';
  $tei2html_service_deployment_page->models = 'fedora-system:ServiceDefinition-3.0';
  $tei2html_service_deployment_page->relationships->add(FEDORA_MODEL_URI, 'isDeploymentOf', 'info:fedora/islandora:tei2htmlSdef');
  $tei2html_service_deployment_page->relationships->add(FEDORA_MODEL_URI, 'isContractorOf', 'info:fedora/islandora:pageCModel');
  // DSINPUTSPEC Datastream
  $datastream = $tei2html_service_deployment_page->constructDatastream('DSINPUTSPEC', 'M');
  $datastream->label = 'DSINPUTSPEC';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_tei2htmlSdep_pageCModel_dsinputspec.xml");
  // METHODMAP Datastream
  $datastream = $tei2html_service_deployment_page->constructDatastream('METHODMAP', 'M');
  $datastream->label = 'METHODMAP';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_tei2htmlSdep_pageCModel_methodmap.xml");
  // WSDL Datastream
  $datastream = $tei2html_service_deployment_page->constructDatastream('WSDL', 'M');
  $datastream->label = 'WSDL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_tei2htmlSdep_pageCModel_wsdl.xml");
  // XSL Datastream
  $datastream = $tei2html_service_deployment_page->constructDatastream('XSL', 'M');
  $datastream->label = 'XSL';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_tei2htmlSdep_pageCModel_xsl.xml");
  // Book Collection
  $book_collection = $connection->repository->constructObject('islandora:bookCollection');
  $book_collection->owner = 'fedoraAdmin';
  $book_collection->label = 'Book Collection';
  $book_collection->models = 'islandora:collectionCModel';
  $book_collection->relationships->add(FEDORA_RELS_EXT_URI, 'isMemberOfCollection', 'info:fedora/islandora:root');
  // Collection Policy Datastream
  $datastream = $book_collection->constructDatastream('COLLECTION_POLICY', 'M');
  $datastream->label = 'COLLECTION_POLICY';
  $datastream->mimetype = 'text/xml';
  $datastream->setContentFromFile("$module_path/xml/islandora_book_collection_policy.xml");
  // TN Datastream
  $datastream = $book_collection->constructDatastream('TN', 'M');
  $datastream->label = 'TN';
  $datastream->mimetype = 'image/png';
  $datastream->setContentFromFile("$module_path/images/folder.png");



  return array(
    'islandora_book'=> array(
      'title' => 'Islandora Books',
      'objects' => array(
        $page_content_model,
        // $bd_page_content_model,
        $ia_book_content_model,
        //$book_content_model,
        //$jp2_service_definition,
        //$jp2_service_deployment_page,
        //$viewer_service_definition,
        //$viewer_service_deployment_book,
        //$viewer_service_deployment_page,
        //$tei2html_service_definition,
        //$tei2html_service_deployment_page,
        $book_collection
      )
    )
  );

  return array(
    'islandora_book' => array(
      'title' => 'Islandora Books',
      // Page C MODEL
      'objects' => array(
        array(
          'pid' => 'islandora:pageCModel',
          'label' => 'Page Content Model',
          'cmodel' => 'fedora-system:ContentModel-3.0',
          'datastreams' => array(
            array(
              'dsid' => 'ISLANDORACM',
              'label' => 'Islandora content model',
              'mimetype' => 'text/xml',
              'control_group' => 'X',
              'datastream_file' => "$module_path/xml/islandora_sp_large_image_cmodel.xml",

            )
          ),
        ),
        // BD Page CModel
        array(
          'foxml_file' => "$module_path/xml/islandora_bd_pageCModel.xml",
          'pid' => 'islandora:bd_pageCModel',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        // ia book c model
        array(
          'foxml_file' => "$module_path/xml/islandora_iaBookCModel.xml",
          'pid' => 'islandora:iaBookCModel',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        // book c model
        array(
          'foxml_file' => "$module_path/xml/islandora_bookCModel.xml",
          'pid' => 'islandora:bookCModel',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        // jp2sdef
        array(
          'foxml_file' => "$module_path/xml/islandora_jp2Sdef.xml",
          'pid' => 'islandora:jp2Sdef',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        // jp2sdep
        array(
          'foxml_file' => "$module_path/xml/islandora_jp2Sdep-pageCModel.xml",
          'pid' => 'islandora:jp2Sdep-pageCModel',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        // viewerddef
        array(
          'foxml_file' => "$module_path/xml/islandora_viewerSdef.xml",
          'pid' => 'islandora:viewerSdef',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        // viewersdep
        array(
          'foxml_file' => "$module_path/xml/islandora_viewerSdep-bookCModel.xml",
          'pid' => 'islandora:viewerSdep-bookCModel',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        // viewerdep
        array(
          'foxml_file' => "$module_path/xml/islandora_viewerSdep-pageCModel.xml",
          'pid' => 'islandora:viewerSdep-pageCModel',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        // teihtmlsdef
        array(
          'foxml_file' => "$module_path/xml/islandora_tei2htmlSdef.xml",
          'pid' => 'islandora:tei2htmlSdef',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        // teihtmldep page
        array(
          'foxml_file' => "$module_path/xml/islandora_tei2htmlSdep-pageCModel.xml",
          'pid' => 'islandora:tei2htmlSdep-pageCModel',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        // org entity
        array(
          'foxml_file' => "$module_path/xml/islandora_organization-entityCModel.xml",
          'pid' => 'islandora:organization-entityCModel',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        // place entity
        array(
          'foxml_file' => "$module_path/xml/islandora_place-entityCModel.xml",
          'pid' => 'islandora:place-entityCModel',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        // person entity
        array(
          'foxml_file' => "$module_path/xml/islandora_person-entityCModel.xml",
          'pid' => 'islandora:person-entityCModel',
          'dsid' => NULL,
          'datastream_file' => NULL,
          'dsversion' => NULL,
        ),
        // book collection
        array(
          'pid' => 'islandora:bookCollection',
          'label' => 'Book Collection',
          'cmodel' => 'islandora:collectionCModel',
          'parent' => 'islandora:root',
          'datastreams' => array(
            array(
              'dsid' => 'COLLECTION_POLICY',
              'datastream_file' => "$module_path/xml/book_collection_policy.xml",
            ),
            array(
              'dsid' => 'TN',
              'datastream_file' => "$module_path/images/Crystal_Clear_filesystem_folder_grey.png",
              'mimetype' => 'image/png',
            ),
          ),
        ),
      ),
    )
  );
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_book_islandora_iabookcmodel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_book_book_view', array('object' => $object));
  return array('' => $output);
}

/**
  * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_book_islandora_bookcmodel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_book_book_view', array('object' => $object));
  return array('' => $output);
}

/**
 * Implements hook_CMODEL_PID_islandora_view_object().
 */
function islandora_book_islandora_pagecmodel_islandora_view_object($object, $page_number, $page_size) {
  $output = theme('islandora_book_page_view', array('object' => $object));
  return array('' => $output);
}


/**
 * Displays the Internet Archive BookReader.
 *
 * @global user $user
 *   Used to pass user credentials to fedora.
 * @param string $object_id
 *   The identifier of the book object to view.
 *
 * @return string
 *   A fieldset containing the Internet Archive BookReader.
 */
function islandora_book_viewer($object_id) {
  global $user;
  $query = ($user->uid != 0) ? '?uid=' . base64_encode($user->name . ':' . $user->pass) : '';
  $viewer_url = variable_get('islandora_base_url', 'http://localhost:8080/fedora');
  $viewer_url .= "/get/{$object_id}/islandora:viewerSdef/getViewer{$query}";
  return theme('fieldset', array(
      '#title' => t('Viewer - @object_id', array('@object_id' => $object_id)),
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
      '#value' => "<iframe src='{$viewer_url}' frameborder='0' scrolling='no' style='width: 100%; height: 800px;'>Errors: unable to load viewer</iframe>"
    )
  );
}

/**
 * Load an xslt from the main book page uses mods for most of the display.
 *
 * @global user $user
 * @param FedoraObject $object
 *   The object to view.
 * @param string $query
 *   Default NULL but if supplied then it will execute the query against the book
 *
 * @return string
 *   The view for books.
 */
function islandora_book_create_book_view(FedoraObject $object, $query = NULL) {
  global $user;
  $xsl = new DOMDocument();
  $xsl->load(drupal_get_path('module', 'islandora_book') . '/xsl/book_view.xsl');
  if (isset($object['MODS'])) {
    $dc = simplexml_load_string($object['DC']->content);
    $types = $dc->xpath('//dc:type');
    $proc = new XSLTProcessor();
    $proc->setParameter('', array(
        'USERID' => $user->uid,
        'OBJECTSPAGE' => base_path(),
        'PID' => $object->id,
        'INGESTED' => in_array('ingested', $types) ? 'TRUE' : 'FALSE',
        'SOLRFIELD' => variable_get('islandora_book_solr_subject_field', 'mods.subject'),
      )
    );
    $input = new DOMDocument();
    if (!$input->loadXML($object['MODS']->content)) {
      drupal_set_message(t('Error loading Book View XML.'));
      return t('Error loading Book View XML.');
    }
    else {
      $proc->importStylesheet($xsl);
      return $proc->transformToXML($input);
    }
  }
}

/**
 * @todo Make each tab into a seperate menu Path.
 */
function islandora_book_islandora_tabs($content_models, $pid) {
  module_load_include('inc', 'islandora_book', 'page_object_manager');
  module_load_include('inc', 'islandora_book', 'book_object_manager');
  module_load_include('inc', 'fedora_repository', 'plugins/FedoraObjectDetailedContent');
  $tabset = array();
  $content_model = $content_models[0]->pid;
  if ($content_model == 'islandora:pageCModel' && user_access(PERM_ISLANDORA_BOOK_MANAGE_PAGE)) {
    $return_tabs = get_page_model_management_content($pid);
    $return_tabs['fedora_object_details'] = null;
    return $return_tabs;
  }
  if ($content_model == 'islandora:bookCModel' || $content_model == 'islandora:iaBookCModel') {
    $return_tabs['fedora_object_details'] = null;
    return $return_tabs;
  }
}
